language: java

env:
  DOCKER_PACKAGE_VERSION: 1.0.${TRAVIS_BUILD_NUMBER}
  IMAGE: thcathy/web-parser-rest
  
jdk:
  - oraclejdk8
  
sudo: required

services:
  - docker
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
after_success:
  - docker build  -t ${IMAGE} .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - ID=`docker images -q ${IMAGE}:latest`
  - docker tag ${ID} ${IMAGE}:${DOCKER_PACKAGE_VERSION}
  - docker tag ${ID} ${IMAGE}:latest
  - docker push ${IMAGE}:${VERSION}
  - docker push ${IMAGE}:latest
