version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:10-jdk-node-browsers
        environment:
              TERM: dumb
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: web-parser-rest-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: web-parser-rest-{{ checksum "build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew check
      - run:
          name: Save test results 
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - run:
          command: ./gradlew jacocoTestReport
      - codecov/upload:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
      - run:
          name: Build Artifacts
          command: ./gradlew assemble
      - persist_to_workspace:
          root: ~/
          paths: 
            - code
  deploy:
    working_directory: ~/code
    docker:
      - image: jdrouet/docker-with-buildx:stable
    steps:      
      - attach_workspace:
          at: ~/
      - setup_remote_docker:
          version: 18.09.3
      - run: |
          TAG=1.0.$CIRCLE_BUILD_NUM
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker buildx build --push \
              --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
              --tag thcathy/web-parser-rest:latest --tag thcathy/web-parser-rest:$TAG .

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build 
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "00 18 * * 5"
          filters:
            branches:
              only: 
                - master
    jobs:
      - build
