pipeline {
  agent {
    docker {
      image 'ansible/ansible-runner'
    }
  }
  parameters {
      imageTag(name: 'DOCKER_IMAGE', description: '',
                   image: 'thcathy/web-parser-rest', filter: '*', defaultTag: 'latest',
                   registry: 'https://registry-1.docker.io', credentialId: '', tagOrder: 'NATURAL')
  }

  environment {
    googleapi_key = credentials('googleapi_key')
    jasypt_encryptor_password = credentials('JASYPT_ENCRYPTOR_PASSWORD')
  }

  stages {
    stage("deploy and verify PROD") {
      when { branch 'master' }
      environment {
        DEPLOY_USER = 'thcathy'
      }
      agent {
        docker {
          image 'ansible/ansible-runner'
        }
      }
      steps {
        ansiblePlaybook(
          inventory: 'ansible/inventory_preprod',
          limit: 'preprod',
          extras: "-e docker_image_tag=${DOCKER_IMAGE_TAG} -e jasypt_encryptor_password=${jasypt_encryptor_password}",
          playbook: 'ansible/deploy.yml',
          credentialsId: 'Jenkins-master'
        )
      }
    }
  }
}
