name: build and deploy to UAT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  jasypt_encryptor_password: ${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
  googleapi_key: ${{ secrets.googleapi_key }}
  dictionaryapi_key: ${{ secrets.dictionaryapi_key }}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: check assemble
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: "build/test-results/test/*.xml"
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: build
        path: build
